---
apiVersion: v1
kind: Service
metadata:
  name: coredns-svc-udp
  namespace: kube-system
  annotations:
    metallb.universe.tf/allow-shared-ip: "DNS_SHARE_IP"
spec:
  selector:
    k8s-app: kube-dns
  type: LoadBalancer
  ports:
    - name: dns-udp
      protocol: UDP
      port: 53
      targetPort: 53
