replicaCount: 1

image:
  repository: "gcr.io/google-samples/microservices-demo/frontend"
  tag: "v0.1.3"

service:
  type: NodePort
  port: 80
  targetPort: 8080
  nodePort: 30001

ingress:
  host: frontend.150.230.151.237.nip.io
  port: 80
