apiVersion: apps/v1
kind: Deployment
metadata:
  name: web
spec:
  replicas: 3
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
      - name: nginx-exporter
        image: docker.io/jora450000/nginx_exporter:0.1
        ports:
        - name: web
          containerPort: 8080
          protocol: TCP
        - name: metrics
          containerPort: 9113
          protocol: TCP
#        args: ['-nginx.scrape-uri', 'http://127.0.0.1:8080/nginx_status']
