apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: nginx-svc-monitor
spec:
  selector:
    matchLabels:
      app: nginx-export-svc
  namespaceSelector:
    matchNames:
    - default
  endpoints:
  - port: metrics
