apiVersion: v1
kind: Service
metadata:
  name: nginx-export-svc
  labels:
    app: web-svc
spec:
  selector:
    app: web
  type: NodePort
  ports:
    - name: web
      protocol: TCP
      port: 8080
      targetPort: web
    - name: metrics
      protocol: TCP
      port: 9113
      targetPort: metrics
