apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: nodeexporter
  labels:
    app: nodeexporter
spec:
  selector:
    matchLabels:
      app: nodeexporter
  template:
    metadata:
      labels:
        app: nodeexporter
    spec:
      containers:
        - image: prom/node-exporter
          name: nodeexporter
          ports:
            - containerPort: 9100
              protocol: TCP
              name: http
      tolerations:
        - key: node-role.kubernetes.io/master
          operator: Exists
          effect: NoSchedule
