apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: nip-issuer
spec:
  acme:
    email: eugene.buravtsov@gmail.com
    server: https://acme-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: nip-ussuer
    solvers:
    - http01:
        ingress:
          class: traefik

