apiVersion: apps/v1
kind: Deployment
metadata:
    name: paymentservice
    labels:
        app: paymentservice
spec:
    replicas: 3
    selector:
        matchLabels:
            app: paymentservice
    strategy:
        type: RollingUpdate
        rollingUpdate:
            maxUnavailable: 1
            maxSurge: 0


    template:
        metadata:
            labels:
                app: paymentservice
        spec:
            containers:
            - name: hipster-paymentservice
              image: docker.io/jora450000/hipstershop-paymentservice:v0.0.2
              ports:
                  - containerPort: 5051
              env:
                  - name: PORT
                    value: "5051"
                  - name: DISABLE_PROFILER
                    value: "1"
