apiVersion: apps/v1
kind: ReplicaSet
metadata:
    name: paymentservice
    labels:
        app: paymentservice
spec:
    replicas: 3
    selector:
        matchLabels:
            app: paymentservice
    template:
        metadata:
            labels:
                app: paymentservice
        spec:
            containers:
            - name: hipster-paymentservice
              image: docker.io/jora450000/hipstershop-paymentservice:v0.0.1
